### ISSUE TITLE
Pin-Order, chip-like and connector-like

### ISSUE THREAD

**Issue by KarlZeilhofer** [xesscorp/KiPart#22]
Is it possible, that the pins on the right side are ordered from top to bottom?

In this case I changed the side from left to right for all pins. Here I could have reversed the sort direction:
![2017-04-18_001](https://cloud.githubusercontent.com/assets/2773445/25151543/387300ca-2486-11e7-8c5f-7df912bbd704.png)

But in this case I got not what I wanted:

What KiPart generated:
![2017-04-18_002](https://cloud.githubusercontent.com/assets/2773445/25151574/4f95321e-2486-11e7-8c66-125b3c286ecf.png)

And what I wanted:
![2017-04-18_003](https://cloud.githubusercontent.com/assets/2773445/25151589/603eca6c-2486-11e7-9a95-c6205d1be1d9.png)

**Comment by xesscorp** [comment]
The solution to your problem is to use the `--sort row` option and arrange the pins in the order you want them in your CSV file. For the right-side pins, that would mean starting with pin 20, then pin 18 on the next row, then pin 16 and so on. For the left-side pins, you would start with pin 1, then pin 3 on the next row, then pin 7 and so on.
